#pragma once

#define TOCPILOT_VERSION_MAJOR 0
#define TOCPILOT_VERSION_MINOR 4
#define TOCPILOT_VERSION_PATCH 1

#define TOCPILOT_VERSION_W L"0.4.1-dev.1"
#define TOCPILOT_VERSION_TAG_W L"v0.4.1-dev.1"
